controller_manager:
  ros__parameters:
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - joint_0 
          - joint_1
          - joint_2
          - joint_3
          - joint_4

        command_interfaces:
          - position

        state_interfaces:
          - position

        open_loop_control: true
        allow_integration_in_goal_trajectories: true
    
    gripper_controller:
      #type: joint_trajectory_controller/JointTrajectoryController
      type: forward_command_controller/ForwardCommandController
      ros__parameters:
        joints:
          - joint_5

        interface_name: position

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# --- Configuração do Curso -----

# controller_manager:
#   ros__parameters:
#     update_rate: 10

#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
          
#     gripper_controller:
#       #type: joint_trajectory_controller/JointTrajectoryController
#       type: forward_command_controller/ForwardCommandController
     
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# arm_controller:
#   ros__parameters:
#     joints:
#       - joint_0 
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position

#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true

# gripper_controller:
#   ros__parameters:
#     joints:
#       - joint_5

#     interface_name: position

#     # command_interfaces:
#     #   - position

#     # state_interfaces:
#     #   - position

#     # open_loop_control: true
#     # allow_integration_in_goal_trajectories: true

# ----- Configuração gepeto ----

# controller_manager:
#   ros__parameters:
#     update_rate: 50

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#       ros__parameters:
#         joints:
#           - joint_0
#           - joint_1
#           - joint_2
#           - joint_3
#           - joint_4
#         command_interfaces:
#           - position
#         state_interfaces:
#           - position
#         open_loop_control: false
#         allow_integration_in_goal_trajectories: true
#         gains:
#           joint_0: {p: 100.0, d: 0.1}
#           joint_1: {p: 100.0, d: 0.1}
#           joint_2: {p: 100.0, d: 0.1}
#           joint_3: {p: 100.0, d: 0.1}
#           joint_4: {p: 100.0, d: 0.1}

#     gripper_controller:
#       type: forward_command_controller/ForwardCommandController
#       ros__parameters:
#         joints:
#           - joint_5
#         interface_name: position



